### ISSUE TITLE
Tracking features not covered by meson

### ISSUE THREAD

**Issue by KaruroChori** [lazy-eggplant/tcc#4]
This issue is just to track which features are not covered by meson right now.  
They have very little priority as they don't interfere with tcc being used inside other projects, but they prevent a fully "standalone" experience:

- [x] ~~Generation of documentation~~ issues tracked in #10 
- [ ] Testsuite 
- [x] Compiler executable (right now it is only provided as library. If used as subproject it should be excluded)
- [x] ~~Generation of examples~~ not needed, they are just documentation. But I am going to add some more for tcc embedding.
- [x] Missing riscv targets
- [x] ~~The current ubuntu image used to build with meson is using a very outdated version. It should be moved to 24.04 I think,~~ resolved by @andy5995 updating it via pip

**Comment by andy5995** [comment]
A couple of general questions: Are you planning to maintain tcc-vs as a fork, or primarily do you just want to have a working meson.build that will make it easier to use this as a subproject? Will you be merging upstream tinycc patches?

**Comment by KaruroChori** [comment]
Good question. My short term plan was just to have it as a "light" fork to cover:
- some patches in functionality I need in the [other place](https://github.com/KaruroChori/vs-fltk). 
- to introduce a minimal meson configuration so that it is possible for me to use it as a library in that and other projects.

Aside from that, I plan to regularly merge commits from upstream and to keep it aligned.  
I have no plan to diverge from the original structure of the repo, except for:
- The "new" README.md and possibly some updated documentation.
- Future github workflows to generate artifacts like the compiled docs and attach them to releases.
- Any file needed to support meson.

This way, once it is in a good state, it is possible to submit a patch to meson-wrapdb and directly link to the [upstream repo](https://repo.or.cz/tinycc.git) which is surely more authoritative :D.
